[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Test utilities shared between crates"
edition = "2021"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "test-utils"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_network"
version = "0.4.11"

[features]
local = ["ant-peers-acquisition/local"]

[dependencies]
ant-peers-acquisition = { path = "../ant-peers-acquisition", version = "0.5.7" }
bytes = { version = "1.0.1", features = ["serde"] }
color-eyre = "~0.6.2"
dirs-next = "~2.0.0"
evmlib = { path = "../evmlib", version = "0.1.4" }
libp2p = { git = "https://github.com/maqi/rust-libp2p.git", branch = "kad_0.46.2", features = ["identify", "kad"] }
rand = "0.8.5"
serde = { version = "1.0.133", features = ["derive"] }
serde_json = "1.0"
